// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// Je charge les variables d'environnement depuis .env
// Cela permet d'utiliser process.env.DATABASE_URL dans Prisma
import "dotenv/config";

// J'importe defineConfig pour déclarer la configuration Prisma
// Ce fichier est lu AVANT le schema.prisma
import { defineConfig } from "prisma/config";

// Je définis la configuration Prisma"
// ATTENTION : je ne dois PAS redéfinir la datasource ici
// car Prisma attend que la datasource soit définie UNIQUEMENT dans schema.prisma
export default defineConfig({
  // Je me dis : "je pointe Prisma vers mon fichier schema.prisma"
  schema: "./prisma/schema.prisma",

  // Je me dis : "je définis où seront stockées les migrations"
  migrations: {
    path: "./prisma/migrations",
  },

  // ❌ Ancienne version (à supprimer)
  // datasource: {
  //   url: process.env["DATABASE_URL"],
  // },

  // Pourquoi supprimer ?
  // → Parce que Prisma n'accepte PAS que la datasource soit définie ici.
  // → Elle doit être définie UNIQUEMENT dans schema.prisma :
  //
  // datasource db {
  //   provider = "postgresql"
  //   url      = env("DATABASE_URL")
  // }
  //
  // Si on la met dans prisma.config.ts, Prisma ignore schema.prisma
  // et déclenche l'erreur P1012 : "Argument url is missing"
});
